USE master;
GO

-- Close existing connections and set the database to single-user mode
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'Evently')
BEGIN
    ALTER DATABASE [Evently] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [Evently];
END
GO 

CREATE DATABASE [Evently];

USE [Evently]

CREATE TABLE [Categories](
	Id UNIQUEIDENTIFIER PRIMARY KEY NONCLUSTERED,
	Name VARCHAR(100) NOT NULL,

	Color VARCHAR(10) NOT NULL,

	Cluster BIGINT IDENTITY(1,1) NOT NULL UNIQUE CLUSTERED
)

CREATE TABLE [Events](
	Id UNIQUEIDENTIFIER PRIMARY KEY NONCLUSTERED,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(100) NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,


	Username VARCHAR(100) NOT NULL,
	CategoryId UNIQUEIDENTIFIER NOT NULL REFERENCES Categories,
	Cluster BIGINT IDENTITY(1,1) NOT NULL UNIQUE CLUSTERED
) 